flask_module/joysticks_app/__init__.py
import os
from flask import Flask
from flask_uwsgi_websocket import GeventWebSocket

def create_app():
    app = Flask(__name__)
    #sockets = GeventWebSocket(app)

    import joysticks_app.controllers as joysticks_app

    app.register_blueprint(joysticks_app.module)
    #app.register_blueprint(joysticks_app.ws)

    return app

flask_module/joysticks_app/controllers.py
from flask import (
    Blueprint,
    render_template,
    Response, 
    make_response,
    request)

import json
from threading import Thread, Event

from joysticks_app.utils import gen_frames, get_map_png, save_map_zone, get_map_zone_png, get_image
# from joysticks_app.test_class import MinimalPublisher, rclpy

module = Blueprint('html', __name__, url_prefix=r'/api')
#ws = Blueprint('ws', __name__, url_prefix=r'/')
data = 0
event = Event()

# def update_field(pub):
#     while True:
#         event.wait()
#         event.clear()
#         pub.timer_callback(data)

# def ros_init():
#     rclpy.init()

#     minimal_publisher = MinimalPublisher()
#     update_field(minimal_publisher)

# Thread(target=ros_init).start()

@module.route(r'/', methods=['GET'])
def index():
    return render_template('index.html')

#@ws.route('/test')
def api(socket):
    global data 
    print('Client connect')
    try:
        while True:
            message = socket.receive()
            data = json.loads(message)
            print(data)
            event.set()
    except TypeError:
        print("client disconect")

@module.route('/video_feed')
def video_feed():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(get_image(), mimetype='multipart/x-mixed-replace; boundary=frame')

@module.route('/<path:path>')
def static_file(path):
    return render_template(path)

@module.route('/get_map', methods=['GET'])
def get_map():
    frame = get_map_png()
    response = make_response(frame)
    response.headers['Content-Type'] = 'image/jpeg'
    return response

@module.route('/get_zone_map', methods=['GET'])
def get_map_zone():
    frame = get_map_zone_png()
    response = make_response(frame)
    response.headers['Content-Type'] = 'image/png'
    return response

@module.route('/load_zone', methods=['POST'])
def load_zone():
    #print(request.form)
    img = request.form.get('image')
    save_map_zone(img)
    return Response('Zone was saved')

@module.route('/load_slam_point', methods=['POST'])
def load_slam_point():
    data = request.json
    return Response('Slam point was saved')

@module.route('/load_nav_point', methods=['POST'])
def load_nav_point():
    return Response('Navigation point was saved')

@module.route('/load_pose', methods=['POST'])
def load_pose():
    return Response('Robot pose was saved')

@module.route('/start_nav', methods=['GET'])
def start_nav():
    return Response('Navigation is working')

@module.route('/stop_nav', methods=['GET'])
def stop_nav():
    return Response('Navigation is stoped')

@module.route('/start_slam', methods=['GET'])
def start_slam():
    return Response('Slam is working')

@module.route('/stop_slam', methods=['GET'])
def stop_slam():
    return Response('Slam is stoped')

@module.route('/save_map', methods=['GET'])
def save_map():
    return Response('Map was saved')

@module.route('/restart_sensors', methods=['GET'])
def restart_sensors():
    return Response('Sensors was restarted')

@module.route('/restart_chassis', methods=['GET'])
def restart_chassis():
    return Response('Chassis was restarted')

@module.route('/restart_system', methods=['GET'])
def restart_system():
    return Response('System was restarted')

@module.route('/remout_control', methods=['GET'])
def remout_control():
    return Response('Remout control was started')

@module.route('/get_states', methods=['GET'])
def get_status():
    return Response('Sensors, chassis and system status')

flask_module/joysticks_app/templates/control.html
<div class="container" style="height: 100%;">
    <div class="col-1-3" style="height: 100%;">
        <div class="row center" style="height: 25%;">
            <input onclick="send_flag('get_states')" type="button" value="Запросить статусы датчиков, шасси и системы" style="height:60px;width:70%">
        </div>
        <div class="row center" style="height: 25%;">
            <input onclick="send_flag('remout_control')" type="button" value="Активировать удаленное управление" style="height:60px;width:70%">
        </div>
        <div class="row" style="height: 50%;">
            <div class="center" style="width: 100%; height: 100%;">
                <img src="../static/images/joystick-base.png" width="50%"/>
            </div>
            <div id="stick3" class="center" style="height: 20%; width: 20%; position: relative; left: 40%; bottom: 60%;">
                <img src="../static/images/joystick-red.png" width="100%"/>
            </div>
        </div>
    </div>
    <div class="col-2-3" style="height: 100%;">
        <div class="col-1-2" style="height: 100%;">
            <div class="row center" style="height: 33%;">
                <input onclick="send_flag('restart_sensors')" type="button" value="Перезапустить датчик" style="height:60px;width:70%">
            </div>
            <div class="row center" style="height: 33%;">
                <input onclick="send_flag('restart_chassis')" type="button" value="Перезапустить шасси" style="height:60px;width:70%">
            </div>
            <div class="row center" style="height: 33%;">
                <input onclick="send_flag('restart_system')" type="button" value="Перезапустить всю систему" style="height:60px;width:70%">
            </div>
        </div>
        <div class="col-1-2" style="height: 100%;">
            <div id="sensor_states" class="row center" style="height: 33%;">
                Статус датчиков
            </div>
            <div id="chassis_states" class="row center" style="height: 33%;">
                Статус шасси
            </div>
            <div id="system_states" class="row center" style="height: 33%;">
                Стутус системы
            </div>
        </div>
    </div>
</div>

<script>
    var joystick3 = new JoystickController("stick3", 64, 8);
</script>

flask_module/joysticks_app/templates/index.html
<!DOCTYPE html>
<html>

	<head>
		<title>Robot Control</title>
		<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/grid.css', v=6) }}">
		<script src='../static/js/joy.js'></script>
		<script src="../static/js/main.js"></script>
		<script src="../static/js/arrow.js"></script>
		<script src="../static/js/map_nav.js"></script>
	</head>

	<body>
		<div id="header" class="row">
		</div>
		<hr>
		<div id="container-header">
			<div class="col-1-4 center" style="height: 100%;"> 
				<input onclick="visible('mapping')" type="button" value="SLAM (построить карту)" style="height:100%; width:70%">
			</div>
			<div class="col-1-4 center" style="height: 100%;">
				<input onclick="visible('map_zone')" type="button" value="Разметка карты"  style="height:100%;width:70%">
			</div>
			<div class="col-1-4 center" style="height: 100%;">	
				<input onclick="visible('navigation')" type="button" value="Навигация по построенной карте"  style="height:100%;width:70%">
			</div>
			<div class="col-1-4 center" style="height: 100%;">
				<input onclick="visible('control')" type="button" value="Удаленное управление роботом"  style="height:100%;width:70%">
			</div>
		</div>
		<hr>
		<div id='content-body' style="height: 600px;">
			<div id="mapping" style="height: 100%; display: none;">
			</div>
			<div id="map_zone" style="height: 100%; display: none;">
			</div>
			<div id="navigation" style="height: 100%; display: none;">
			</div>
			<div id="control" style="height: 100%; display: none;">
			</div>
		</div>
		<hr>
		
		<div id='footer' class="row">
		</div>

		<div id="loading" style="display: none">
			Идет загрузка...
		</div>
	</body>

	<script>
		$(document).ready(function() {
			update_height();
			load_content("mapping");
			load_content("map_zone");
			load_content("navigation");
			load_content("control");

			var container_header = document.getElementById('container-header');
			var inputs = container_header.querySelector('input');
			loop();
		 });
		$(window).resize(function(){
			update_height()
		});
		function update_height(){
			document.getElementById("content-body").style.height = $(window).height()*0.75+"px";
			document.getElementById("container-header").style.height = $(window).height()*0.05+"px";
			document.getElementById("header").style.height = $(window).height()*0.05+"px";
			document.getElementById("footer").style.height = $(window).height()*0.1+"px";
		}
	</script>

</html>

flask_module/joysticks_app/templates/map_zone.html
<div class="container" style="height: 100%;">
    <div class="row" style="height: 100%;">
        <div class="col-1-2" style="height: 100%;">
            <div id="map" class="col-1-2" style="height: 100%; height: 100%;">
                <canvas id="canvasMap" width="500px" height="500px" style="position: relative; left: 50%; "></canvas>
                <canvas id="canvasObv" width="500px" height="500px" style="position: relative; left: 50%; transform: translate(0%, -100%); background:transparent;"></canvas>
            </div>
        </div>
        <div class="col-1-2" style="height: 100%;">
            <div class="row center" style="height:  25%;">
                <input onclick="create_zone()" type="button" value="Добавить запрещенные зоны" style="height:60px;width:70%">
            </div>
            <div class="row center" style="height: 25%;">
                <input onclick="delete_zone()" type="button" value="Редактировать запрещенные" style="height:60px;width:70%">
            </div>
            <div class="row center" style="height: 25%;">
                <input onclick="clear_zone()" type="button" value="Убрать запрещенные зоны" style="height:60px;width:70%">
            </div>
            <div class="row center" style="height: 25%;">
                <input onclick="save_zone()" type="button" value="Сохранить запрещенные зоны" style="height:60px;width:70%">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="../static/js/map_zone.js"></script>

<script>
    $(document).ready(function() {
        load_img_canvas('canvasMap', "get_map");
        load_img_canvas('canvasObv','get_zone_map');
        InitThis('canvasObv');
    }); 
</script>

flask_module/joysticks_app/templates/mapping.html
<div class="container" style="height: 100%;">
    <div class="row" style="height: 100%;">
        <div class="col-1-2 center">
            <img id='map_stream_slam' src="{{ url_for('html.video_feed') }}" width="70%"/>
        </div>

        <div class="col-1-2" style="height: 100%;">
            <div class="row" style="height: 20%;">
                <div class="col-1-2 center">
                    <input id='get_point_slam' onclick="get_point_slam()" type="button" value="Задать целевую точку" style="height:60px;width:70%">
                </div>
                <div class="col-1-2 center">
                    <input onclick="send_flag('start_slam')" type="button" value="Запустить SLAM" style="word-break: break-all; height:60px;width:70%">
                </div>
            </div>

            <div class="row" style="height: 70%;">
                <div class="col-1-2" style="height: 100%;">
                    <div class="center" style="width: 100%; height: 100%;">
                        <img src="../static/images/joystick-base.png" width="50%"/>
                    </div>
                    <div id="stick1" class="center" style="height: 20%; width: 20%; position: relative; left: 40%; bottom: 60%;">
                        <img src="../static/images/joystick-red.png" width="100%"/>
                    </div>
                </div>
                <div class="col-1-2" style="height: 100%;">
                    <div class="row center" style="height: 50%;">
                        <input onclick="send_flag('save_map')" type="button" value="Сохранить построенную карту" style="height:60px;width:70%">
                    </div>
                    <div class="row center" style="height: 50%;">
                        <input onclick="send_flag('stop_slam')" type="button" value="Остановить SLAM" style="height:60px;width:70%">
                    </div>
                </div>
            </div>

            <div class="row center" style="height: 10%;">
                <p>Статус</p>
            </div>
        </div>
    </div>
</div>

<script>
    var joystick1 = new JoystickController("stick1", 64, 8);
    try{
    var arrow_slam = new Arrow('map_stream_slam', "load_slam_point", "get_point_slam");
    }
    catch (e){
        alert("slam"+e);
    }
    
    function get_point_slam(){
        arrow_slam.flag_point = true;
        arrow_slam.cliked = 0;
    }
</script>

flask_module/joysticks_app/templates/navigation.html
<div class="container" style="height: 100%;">
    <div class="row" style="height: 100%;">
        <div class="col-1-2 center">
            <img id='map_stream_nav' src="{{ url_for('html.video_feed') }}" width="70%"/>
        </div>

        <div class="col-1-2" style="height: 100%;">
            <div class="row" style="height: 20%;">
                <div class="col-1-2 center">
                    <input id="get_point_nav" onclick="get_point_nav()" type="button" value="Задать целевую точку" style="height:60px;width:70%">
                </div>
                <div class="col-1-2 center">
                    <input onclick="send_flag('start_nav')" type="button" value="Запустить навигацию" style="word-break: break-all; height:60px;width:70%">
                </div>
            </div>

            <div class="row" style="height: 70%;">
                <div class="col-1-2" style="height: 100%;">
                    <div class="center" style="width: 100%; height: 100%;">
                        <img src="../static/images/joystick-base.png" width="50%"/>
                    </div>
                    <div id="stick2" class="center" style="height: 20%; width: 20%; position: relative; left: 40%; bottom: 60%;">
                        <img src="../static/images/joystick-red.png" width="100%"/>
                    </div>
                </div>
                <div class="col-1-2" style="height: 100%;">
                    <div class="row center" style="height: 50%;">
                        <input onclick="send_flag('stop_nav')" type="button" value="Остановить навигацию" style="height:60px;width:70%">
                    </div>
                    <div class="row center" style="height: 50%;">
                        <input id="set_pose" onclick="set_pose()" type="button" value="Указать текущую позицию и ориентацию робота" style="height:60px;width:70%">
                    </div>
                </div>
            </div>

            <div class="row center" style="height: 10%;">
                <p>Статус</p>
            </div>
        </div>
    </div>
</div>

<script>
    var joystick2 = new JoystickController("stick2", 64, 8);

    var arrow_nav = new Arrow('map_stream_nav', "load_nav_point", "get_point_nav");
    var arrow_pose = new Arrow('map_stream_nav', "load_pose", "set_pose");

    function get_point_nav(){
        arrow_nav.flag_point = true;
        arrow_nav.cliked = 0;
    }

    function set_pose(){
        arrow_pose.flag_point = true;
        arrow_pose.cliked = 0;
    }
</script>